### ISSUE TITLE
Can't override boolean with default value set to true

### ISSUE THREAD

**Issue by frontierpsycho** [voxelbrain/goptions#23]
I'd like to add this global option:

```Dry        bool         `goptions:"-d, --dry, description='do a dry run'"` ```

and set its default value to `true`. However, I cannot override that in the command line: when I pass `--dry=false`, I get `Error: Invalid trailing arguments: [--dry=false ...`.

I tried the same with regular flags, and it was possible.

Is this something that can be fixed?

**Comment by surma** [comment]
Oooh, interesting. I don’t think I ever thought of that use-case. 

As of now, there is no way for that behavior. I’d recommend inverting the semantics of the flag. So instead of calling it “Do a dry run” call it “Actually perform action” or something.

I might add this behavior in the future, but for not it’s not worth the effort as it requires some major refactorization in the data structures (PRs welcome).

**Comment by frontierpsycho** [comment]
Ah, right. Yes, I thought of inverting the semantics, it just feels a bit unnatural. Thanks for verifying it, anyway!
